version: '3.4'

services:
  catalog.api:
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - "ConnectionStrings__OrderingConnection=server=catalogdb;Database=DWshopDiciembre;Encrypt=false;user id=sa;pwd=Hola123!"
    ports:
      - "8000:80"
    container_name: "catalog.api"
    depends_on:
      - catalogdb
 
      
  catalogdb:
   container_name: "catalogdb"
   environment:
      SA_PASSWORD: "Hola123!"
      ACCEPT_EULA: "Y" 
   ports:
     - 1433:1433 



  basket.api:
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - "ConnectionStrings__BasketConnection=server=catalogdb;Database=DWshopDiciembre_Basket;Encrypt=false;user id=sa;pwd=Hola123!"
      - "EventBusSettings__HostAddress=amqp://guest:guest@rabbitmq:5672"
    ports:
      - "8001:80"
    container_name: "basket.api"
    depends_on:
     - rabbitmq
     - catalogdb

  rabbitmq:
    container_name: rabbitmq
    ports:
     - "5672:5672"
     - "15672:15672"


  ordering.api:
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - "EventBusSettings__HostAddress=amqp://guest:guest@rabbitmq:5672"
      - "ConnectionStrings__OrderingConnectionString=server=catalogdb;Database=DWshopDiciembre_Ordering;Encrypt=false;user id=sa;pwd=Hola123!"
      #puertos
    ports:
      - "8002:80"
    container_name: ordering.api
    depends_on:
     - rabbitmq
     - catalogdb


  api.gateway:
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
    ports:
      - "8003:80"
    container_name: api.gateway

