version: '3.4'

services:
  catalog.api:
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - "ConnectionStrings__OrderingConnection=server=catalogdb;Database=DWshopDiciembre;Encrypt=false;user id=sa;pwd=Hola123!"
    ports:
      - "8000:80"
    container_name: "catalog.api"
    depends_on:
      - catalogdb
 
      
  catalogdb:
   container_name: "catalogdb"
   environment:
      SA_PASSWORD: "Hola123!"
      ACCEPT_EULA: "Y" 
   ports:
     - 1433:1433 


